### ISSUE TITLE
Removing nodejs bug squishing

### ISSUE THREAD

**Issue by naemr** [binarysec/gate#50] opened 2017-02-24 06:51 UTC
```
if test `ls ./deps/nodejs | wc -l` -eq 0; then make git-submodules-up; fi
ls: cannot access ./deps/nodejs: No such file or directory
make[1]: Entering directory `/root/gate/gate'
git submodule update --init --recursive
make[1]: Leaving directory `/root/gate/gate'
cd ./deps/nodejs && ./configure --prefix="/usr/local/share/gatejs/node"
/bin/sh: 1: cd: can't cd to ./deps/nodejs
make: *** [all] Error 2
```

seems the autocompile system failed after https://github.com/binarysec/gate/commit/dd66c2ce12dcdd6b35e0a25d61162779db779b09

also 

> SSL options are provided by node.js

still possible to proxy ssl?

**Comment by mykiimike** [comment] 2017-02-24 13:25
Hi,

Yes i removed the nodes deps. We gonna fix the compilation issue but you will have to install at least node 4.x

And yes we still proxy ssl :)

**Comment by mykiimike** [comment] 2017-02-25 14:15
Try

```bash
npm install -g gatejs
```

**Comment by naemr** [comment] 2017-02-26 04:09
> npm install -g gatejs


[npm-debug.txt](https://github.com/binarysec/gate/files/801716/npm-debug.txt)

**Comment by mykiimike** [comment] 2017-02-26 07:34
Thanks, i missed a path

You can try it again

**Comment by naemr** [comment] 2017-02-26 16:03
Seems to be a few more things needing a dose of raid
[gatenpm.txt](https://github.com/binarysec/gate/files/802075/gatenpm.txt)

in the event it matters:
`
3.19.0-25-generic #26~14.04.1-Ubuntu SMP
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
`

**Comment by Dagrut** [comment] 2017-02-27 07:37
I fixed the gatejs start file, however the warnings may be caused by the nodejs version. (Probably v6, because with node v4 it builds without any warnings).

**Comment by Dagrut** [comment] 2017-02-28 09:59
The warnings were also fixed in yeserday & today's commits.

**Comment by Dagrut** [comment] 2017-03-03 09:20
Travis build is passing. If anything else still fails, just post it here. For now, I'll close this issue :)

**Comment by naemr** [comment] 2017-03-04 17:02
`npm install -g gatejs`

[npm-debug.txt](https://github.com/binarysec/gate/files/818776/npm-debug.txt)

`$ git clone https://github.com/binarysec/gate.git gate
$ cd gate
$ npm install`

[gitgate.txt](https://github.com/binarysec/gate/files/818782/gitgate.txt)

**Comment by naemr** [comment] 2017-03-05 15:06
Also happening on 4.4.0-64-generic #85-Ubuntu 16.04.2 LTS

**Comment by mykiimike** [comment] 2017-03-05 16:24
Make sure you have **make** installed on your system. 

try this :**sudo apt-get install build-essential make**

And then **sudo npm install -g gatejs**

Or try the git version.

Sorry for the NPM transition :)

Thanks
mykii

**Comment by naemr** [comment] 2017-03-15 02:17
make/build-essential were both installed and up to date, also the git version was tried as per my last post.

sorry for my long delays in getting back, i travel quite a bit for work and time/internet is not always "a thing" for me

**Comment by Dagrut** [comment] 2017-03-15 05:40
Okay, that seems really weird... I just installed a fresh ubuntu 16.04 inside virtualbox, installed `build-essential` (which requires `make`), `python` and then `nodejs` (from the deb.nodesource repo/sh script) and finally installed gatejs with npm (`npm install -g gatejs` as root), and there was no bug for me.
The makefile was updated this week so it may solve your problem, however it seems that npm cannot find `make`, which is not normal.

Maybe you could try once again to install it. Also could you tell us :

- The output of `which npm`
- The output of `which make`
- The output of `echo $PATH`
- How did you install nodejs?

**Comment by mykiimike** [comment] 2017-03-15 07:06
@Dagrut he seems to use an Ubuntu 14.04

**Closed** 2017-03-30 21:41 UTC
Labels: bug
